version: '3.8'

services:

  # memcached:
  #   image: memcached
  #   container_name: memcached
  #   ports:
  #     - "11211:11211"
  #   command: memcached -m 64
  #   restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped