# Generated by Django 4.1.13 on 2024-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_email_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='s@g.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
