# Generated by Django 4.2 on 2024-03-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog_post_publish_bb7600_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
    ]
